# ──────────────────────────────────────────────────
#  ________  ________  ________
# |\   ____\|\   __  \|\   __  \
# \ \  \___|\ \  \|\  \ \  \|\ /_
#  \ \  \    \ \  \\\  \ \   __  \
#   \ \  \____\ \  \\\  \ \  \|\  \
#    \ \_______\ \_______\ \_______\
#     \|_______|\|_______|\|_______|
# ──────────────────────────────────────────────────

# ──────────────────────────────────────────────────
# Status / Presence
# ──────────────────────────────────────────────────
# The status cycles through this list
statusType: "online"
statusMessages:
    - "─ CORN ───"
    - "── CORN ──"
    - "─── CORN ─"
    - "── CORN ──"
