# ──────────────────────────────────────────────────
#  ________  ________  ________
# |\   ____\|\   __  \|\   __  \
# \ \  \___|\ \  \|\  \ \  \|\ /_
#  \ \  \    \ \  \\\  \ \   __  \
#   \ \  \____\ \  \\\  \ \  \|\  \
#    \ \_______\ \_______\ \_______\
#     \|_______|\|_______|\|_______|
#
# Bot Settings
# ──────────────────────────────────────────────────

# ──────────────────────────────────────────────────
# Bot Info
# ──────────────────────────────────────────────────
name: "COB"
botId: "1166951538086912101"

# ──────────────────────────────────────────────────
# Status / Presence
# ──────────────────────────────────────────────────
statusType: "idle"
# The status cycles through this list
statusMessages:
    # Going for an animation here
    - "|─ CORN ──|"
    - "|─── CORN |"
    - "|───── COR|"
    - "|N ───── C|"
    - "|ORN ─────|"
    - "| CORN ───|"

# ──────────────────────────────────────────────────
# Colors / Embed
# ──────────────────────────────────────────────────
colors:
    invis: "#2b2d31"
    # Using https://colordesigner.io/#000137-29003F-79003D-D04D14-F89801
    primary: "#79003D"
    secondary: "#29003F"
    accent: "#F89801"
    success: "#1ABC9C"
    error: "#E74C3C"

